### ISSUE TITLE
No web interface (?) - 7.5.1 on Ubuntu 20.04

### ISSUE THREAD

**Issue by sabashuali** [fcole90/fah-snap#11]
Installed the F@H app from the Ubuntu store.  Client is running fine but I have the following issues:

- only have the F@H control, i.e unable to launch the web interface.

- In the app control, when going to configure > advance, COVID-19 is not listed in the "Cause Preference" drop down menu.

- I have two "Folding At Home " icons in my app list as shown in the attached image. when I click on either I receive an error - "Failed to Launch Folding at Home - Desktop file didn't specify exec field"
![Apps view](https://user-images.githubusercontent.com/67744333/86371183-81eb4b80-bc78-11ea-9f85-4e81f8370c1f.png)

**Comment by fcole90** [comment]
Thank you for reporting this :blush: 
If I understood correctly these are 3 issures, right?

 - no web interface
 - cause preference not shown
 - two non-functional Folding at Home icons

Is this correct? If yes, I will create one report for each issue

**Comment by sabashuali** [comment]
Hi and thanks for getting back to me!
I wasn't sure whether they are three separate issues or three symptoms of the one... :-)
But if it helps, then please go ahead. 

Subsequently, I moved away from Ubuntu as it was not the user experience I was after and I am now happily using Debian 10.  I installed the deb packages offered on F@H site and everything is working splendidly.

If this means you cannot continue with your investigation then I am truly sorry for wasting your time... 

All the best, Oren

**Comment by fcole90** [comment]
Great to here everything is fine for you. If at some point you want, snaps are supported in Debian as well.
Don't worry, I'll try to investigate the issue as soon as I have some spare time.

Best,
Fabio

**Comment by lucamanga** [comment]
I think that the problem is the Python 3 support. It will end in Debian 11, too.

**Comment by fcole90** [comment]
Hi, I think you meant that python2 support has come to an end. While this is true, the python2 interpreter is shipped within the package so that's unlikely to be the actual cause.

**Comment by fcole90** [comment]
Hi @sabashuali, given that you are using the deb, can you tell me if there `COVID-19 ` is listed in the "Cause Preference" drop down menu? I think to remember you need to keep it empty to select COVID19, am I wrong?

**Comment by fcole90** [comment]
On my system, if I launch FAH first, then I can check the web interface from https://client.foldingathome.org/ . Does it work for you?

**Comment by fcole90** [comment]
I confirm the issue with the two icons, I'm going to investigate that for the moment

**Comment by fcole90** [comment]
Fix for the two icons: https://github.com/fcole90/fah-snap/commit/2e6fab26829654f1a63b4e18b30b9b4cf4c4ceaa
