### ISSUE TITLE
Text is displayed as boxes

### ISSUE THREAD

**Issue by 1Maxnet1** [fcole90/fah-snap#14]
When I install folding@home snap on computer, it looks like this:
![grafik](https://user-images.githubusercontent.com/24827631/105682160-5ec50980-5ef2-11eb-8987-a285668a14ea.png)
System: Manjaro Linux KDE

**Comment by fcole90** [comment]
Thanks for reporting your issue. This is a duplicate of #12 . You can check some workarounds on the link https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/90
Have a good day :blush:

**Comment by fcole90** [comment]
Duplicate of #12
