### ISSUE TITLE
Opencl not detected: failed to open dynamic library 'libOpenCL.so' libOpenCL.so: cannot open shared object file: no such file or directory

### ISSUE THREAD

**Issue by aluisell** [fcole90/fah-snap#6]
Hi, I'm using ubuntu 19.10, downloaded FAHClient directly from Ubuntu X11 application. I'm using a Nvidia GTX 1080 with Nvidia driver (coming from original website.
Ubuntu is fully up to date. I also installed ocl-icd-opencl-dev package but still got this error.
I tried to modify the FAHClient script to make it using root user instead of fahclient (i found in some tread the suggestion to use root) but got error no read only file system.

I'm sorry but I don't know how to change snap environment/files
Have you tried to run the script as different user already?

Anything else I can try? Thanks

**Comment by fcole90** [comment]
Hi, can you remove and reinstall the snap? While I couldn't make OpenCL work yet, the latest version should at least detect your GPU.

```
sudo snap remove folding-at-home-fcole90
sudo snap install folding-at-home-fcole90 
sudo snap connect folding-at-home-fcole90:hardware-observe 
folding-at-home-fcole90 --configure
folding-at-home-fcole90
```

Now it should at least detect your GPUs and no longer report a missing `'libOpenCL.so`.

**Comment by fcole90** [comment]
I'm not sure how well does it work in Ubuntu, to install nvidia drivers from their website. So, I'd recommend, **before reinstalling the snap** to remove the nvidia driver you downloaded and instead use the ones that are provided by Ubuntu, (e.g. `nvidia-driver-435`)

**Comment by aluisell** [comment]
Hi, I did some more test and tried again from a clean Ubuntu install following below steps:
1) install ubuntu 19.10 from scratch with 3d party driver/option
2) completed all the software udpate,
3) I have followed the instruction here for standard install (https://askubuntu.com/questions/1217195/how-to-install-folding-at-home-foldinghome-fahcontrol-on-ubuntu-19-10)
4) at that point didn't work yet... and was getting same error of missing libOpenCL.so
5) i have installed sudo apt install ocl-icd-opencl-dev
6) rebooted again and now no error but still saying GPU 0 
7) I noticed that /etc/fahclient/config.xml was still with wrong parameter (gpu false) because I have lunched it previously and it didn't detected the GPU). Modified to "true" 
8) rebooted and got it working! :)

did you check the value in your config.xml file?

Just to be clear, it worked using Folding@home version not your snap package and above the steps I used to make it working.

**Comment by fcole90** [comment]
I'm very happy you got it working :blush: However, this repo is only about the snap specific matter. Next time you encounter some issue with FAH not using the snap, you can report them on https://github.com/FoldingAtHome/fah-issues/issues :wink:
